### ISSUE TITLE
[JOSS Review] Generate Article Proof

### ISSUE THREAD

**Issue by praneethd7** [EleutherAI/ccs#12]
Hello, @lauritowal. I was trying to generate the pdf using the editorial bot and there seems to be some issue with it: https://github.com/openjournals/joss-papers/actions/runs/10997679682?check_suite_focus=true

I am not sure if it has something to do with JOSS or your file.  Can you confirm if this is the latest version of the pdf?
https://github.com/openjournals/joss-papers/blob/joss.06511/joss.06511/10.21105.joss.06511.pdf

Cross Ref: **https://github.com/openjournals/joss-reviews/issues/6511**
Thank you!
-Praneeth

**Comment by lauritowal** [comment]
please retry, I think I messed up something in the yaml. It should work now. @praneethd7

**Comment by praneethd7** [comment]
Hmm. Seems like that did not work. Did you setup JOSS to pickup the correct branch?
https://github.com/openjournals/joss-papers/actions/runs/10997941483/job/30534696426

**Comment by lauritowal** [comment]
It seems like I set it to _joss-paper_, but it's trying to get it from _joss_ maybe?

```
Submitting author: @lauritowal ([Walter Laurito](http://orcid.org/0000-0002-6431-7053))
Repository: https://github.com/EleutherAI/ccs
**Branch with paper.md (empty if default branch): joss-paper**
```

**Comment by lauritowal** [comment]
ah wait, I haven't actually merged my previous changes. I'll let you know once this is done.

**Comment by lauritowal** [comment]
@praneethd7 the changes are merged now
